# Generated by Django 4.1.1 on 2023-06-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppIcon', models.ImageField(upload_to='img')),
                ('AppName', models.CharField(max_length=100)),
                ('AppLink', models.CharField(max_length=100)),
                ('AppCategory', models.CharField(max_length=100)),
                ('AppSubCategory', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
    ]
