# Generated by Django 4.1.1 on 2023-06-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDS_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetails',
            name='AppIcon',
            field=models.ImageField(upload_to='AppIcons'),
        ),
    ]
